#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse
from toolbox.lib import send_sms


# Import from toolbox
import toolbox
from toolbox.lib import clean_data

if __name__ == '__main__':
    usage = '%(prog)s'
    description = 'toolbox_description'
    # https://docs.python.org/3/library/argparse.html
    # https://docs.python.org/3/howto/argparse.html
    parser = argparse.ArgumentParser(description=description, usage=usage)
    args = parser.parse_args()
    send_sms()
